

#PATH=$PATH:$HOME/projects/deep-toolkit/linux/bin:~/opt/bin:~/opt/gtags/bin:~/bin:~/opt/lcov/bin:~/projects/git/video_pay_dev_tool/bin
PATH=$PATH:$HOME/projects/toolkit/linux/bin:~/opt/bin:~/opt/gtags/bin:~/bin:~/opt/lcov/bin
export PATH

#LD_LIBRARY_PATH="/usr/local/commlib/outerlib/nameapi/lib"
#LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/data/home/deepliu/opt/gcc-4.8.5/lib64"
#LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/data/home/deepliu/opt/python-3.6.5/lib:/data/home/deepliu/opt/python-3.6.5/lib/python3.6/lib-dynload"
#export LD_LIBRARY_PATH

alias rm="rm -i"
alias cp="cp -i"
alias mv='mv -i'
alias grep="grep --color"

#alias cmake="/usr/bin/cmake"
alias remake="make clean; make -j8"

VIMPATH=/data/opt/vim82
alias vim="${VIMPATH}/bin/vim -u ${VIMPATH}/etc/vimrc"
alias view="${VIMPATH}/bin/view -u ${VIMPATH}/etc/vimrc"
alias vi="${VIMPATH}/bin/vim -u ${VIMPATH}/etc/vimrc"
alias vimdiff="${VIMPATH}/bin/vimdiff -u ${VIMPATH}/etc/vimrc"
alias xxd="${VIMPATH}/bin/xxd -u ${VIMPATH}/etc/vimrc"
#alias git="~/opt/git/bin/git"

#alias ctags="~/opt/bin/ctags"

#alias myproto="cd ~/projects/all_projects/inter_comm/pay_all_proto/"

alias vimp="vim +Project"
alias opensources="vim -M +'Project ~/vimprojects/opensources'"
#alias opensources="vim +'Project ~/vimprojects/opensources'"

alias urldecode='python -c "import sys, urllib as ul; \
    print ul.unquote_plus(sys.argv[1])"'
alias urlencode='python -c "import sys, urllib as ul; \
    print ul.quote_plus(sys.argv[1])"'

export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

#export GTAGSLIBPATH=$GTAGSLIBPATH:/usr/include:/usr/local/commlib/outerlib/:~/projects/all_projects/inter_comm/ # seems not working
export TERM=xterm-256color # for vim
